apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit
  labels:
    name: streamlit
spec:
  rules:
  - host: lancelot-streamlit.lab.sspcloud.fr
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: streamlit
            port: 
              number: 8080
