apiVersion: v1
kind: Service
metadata:
  name: streamlit
  labels:
    app: streamlit
  namespace: user-lmarti
spec:
  selector:
    app: streamlit
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30500
  type: NodePort
