name: Push Charts to Another Repo

on: 
  push: 
    branches:
    - main
    - hotfix/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.TOKEN }}
      with:
        source-directory: test2/charts/
        destination-github-username: 'LancelotMarti'
        destination-repository-name: 'sandbox'
        target-branch: main
        target-directory: charts/